// Mocks generated by Mockito 5.0.14 from annotations
// in clementoni/test/features/products/domain/usecases/get_product_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:clementoni/core/error/failures.dart' as _i5;
import 'package:clementoni/features/products/domain/entities/product.dart'
    as _i7;
import 'package:clementoni/features/products/domain/entities/products.dart'
    as _i6;
import 'package:clementoni/features/products/domain/repositories/products_repository.dart'
    as _i3;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeEither_0<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

/// A class which mocks [ProductsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductsRepository extends _i1.Mock
    implements _i3.ProductsRepository {
  MockProductsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Products>> getProducts() =>
      (super.noSuchMethod(Invocation.method(#getProducts, []),
              returnValue: Future<_i2.Either<_i5.Failure, _i6.Products>>.value(
                  _FakeEither_0<_i5.Failure, _i6.Products>()))
          as _i4.Future<_i2.Either<_i5.Failure, _i6.Products>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, _i7.Product>> getProduct(int? id) =>
      (super.noSuchMethod(Invocation.method(#getProduct, [id]),
              returnValue: Future<_i2.Either<_i5.Failure, _i7.Product>>.value(
                  _FakeEither_0<_i5.Failure, _i7.Product>()))
          as _i4.Future<_i2.Either<_i5.Failure, _i7.Product>>);
  @override
  String toString() => super.toString();
}
