// Mocks generated by Mockito 5.0.14 from annotations
// in clementoni/test/features/products/data/repositories/products_repository_impl_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:clementoni/core/network/internet_connection.dart' as _i7;
import 'package:clementoni/features/products/data/datasources/products_local_data_source.dart'
    as _i6;
import 'package:clementoni/features/products/data/datasources/products_remote_data_source.dart'
    as _i4;
import 'package:clementoni/features/products/data/models/product_model.dart'
    as _i3;
import 'package:clementoni/features/products/data/models/products_model.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeProductsModel_0 extends _i1.Fake implements _i2.ProductsModel {}

class _FakeProductModel_1 extends _i1.Fake implements _i3.ProductModel {}

/// A class which mocks [ProductsRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductsRemoteDataSource extends _i1.Mock
    implements _i4.ProductsRemoteDataSource {
  MockProductsRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.ProductsModel> getProducts() => (super.noSuchMethod(
          Invocation.method(#getProducts, []),
          returnValue: Future<_i2.ProductsModel>.value(_FakeProductsModel_0()))
      as _i5.Future<_i2.ProductsModel>);
  @override
  _i5.Future<_i3.ProductModel> getProduct(int? id) => (super.noSuchMethod(
          Invocation.method(#getProduct, [id]),
          returnValue: Future<_i3.ProductModel>.value(_FakeProductModel_1()))
      as _i5.Future<_i3.ProductModel>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [ProductsLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductsLocalDataSource extends _i1.Mock
    implements _i6.ProductsLocalDataSource {
  MockProductsLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.ProductsModel> getLocalProducts() => (super.noSuchMethod(
          Invocation.method(#getLocalProducts, []),
          returnValue: Future<_i2.ProductsModel>.value(_FakeProductsModel_0()))
      as _i5.Future<_i2.ProductsModel>);
  @override
  _i5.Future<bool> saveProductsLocally(_i2.ProductsModel? products) =>
      (super.noSuchMethod(Invocation.method(#saveProductsLocally, [products]),
          returnValue: Future<bool>.value(false)) as _i5.Future<bool>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [InternetConnection].
///
/// See the documentation for Mockito's code generation for more information.
class MockInternetConnection extends _i1.Mock
    implements _i7.InternetConnection {
  MockInternetConnection() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<bool> get isConnected =>
      (super.noSuchMethod(Invocation.getter(#isConnected),
          returnValue: Future<bool>.value(false)) as _i5.Future<bool>);
  @override
  String toString() => super.toString();
}
